#!/usr/bin/env node
/* Generate Hindawi transducers for a language written in a NON-Devanagari
 * script, both directions, in the form that actually builds.
 *
 * THE ARCHITECTURE, as proven on the live system:
 *
 *   A transducer for such a language is itself written in <शैली शब्द> (lex).
 *   Its source passes through the SAME chain as a user program:
 *
 *     cat X.uhin | fixuninum | fltr_<lang>_hi | iconv -f utf-8 -t utf-16 \
 *       | uni2acii | acii2cf | tail +2 > X.lex
 *
 *   so an Urdu pattern and an Urdu program token both arrive at flex as the
 *   same romenagri string and match.
 *
 * TWO RULES THAT WERE LEARNED THE HARD WAY:
 *
 *   1. FORWARD actions must be PLAIN ASCII host keywords, and the generated
 *      .lex must NEVER be piped through h2c. Doing so transduces the PATTERN
 *      column as well: `waapasa {printf("return");}` became
 *      `return {printf("return");}` and the rule stopped matching anything.
 *
 *   2. REVERSE actions are written in the source language. They pass through
 *      the chain to romenagri, so the reverse tool's OUTPUT is piped through
 *      fltr_hi_<lang> to come back into the native script.
 */
import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEG = path.join(root, 'retrieved/legacy/Hindawi');

const split=(l)=>{const o=[];let c='',q=false;
  for(let i=0;i<l.length;i++){const ch=l[i];
    if(q){if(ch==='"'&&l[i+1]==='"'){c+='"';i++;}else if(ch==='"')q=false;else c+=ch;}
    else if(ch==='"')q=true;else if(ch===','){o.push(c);c='';}else c+=ch;}
  o.push(c);return o;};
const raw=fs.readFileSync(path.join(root,'ilm/keywords.csv'),'utf8').replace(/\r/g,'').split('\n').filter(Boolean);
const head=split(raw[0]);
const rows=raw.slice(1).map((l)=>Object.fromEntries(split(l).map((v,i)=>[head[i],v])));

const SH = {
  guru:{host:'C', fwd:'h2c', rev:'c2h', src:'guru/h2c.uhin', drv:'gurucc', tool:'cc', ext:'.c', pipe:[]},
  praatha:{host:'BASIC', fwd:'h2b', rev:'b2h', src:'praatha/h2b.uhin', drv:'praathacc', tool:'qb2c', ext:'.bas', pipe:[]},
  shraeni:{host:'C++', fwd:'h2cpp', rev:'cpp2h', src:'shraeni/h2cpp.uhin', drv:'shraenicc', tool:'c++', ext:'.cpp', pipe:[]},
  kritrima:{host:'Java', fwd:'h2j', rev:'j2h', src:'kritrima/h2j.uhin', drv:'kritrimacc', tool:'javac', ext:'.java', pipe:[]},
  soochee:{host:'Python', fwd:'h2py', rev:'py2h', src:'soochee/h2py.uhin', drv:'soocheecc', tool:'python3', ext:'.py', pipe:[]},
  shabda:{host:'lex', fwd:'h2l', rev:'l2h', src:'shabda/h2l.uhin', drv:'shabdacc', tool:'flex', ext:'.l', pipe:['h2c']},
  wyaaka:{host:'yacc', fwd:'h2yacc', rev:'yacc2h', src:'wyaaka/h2yacc.uhin', drv:'wyaakacc', tool:'bison', ext:'.y', pipe:['h2c']},
  yantra:{host:'asm', fwd:'h2y', rev:'y2h', src:'yantra/h2y.uhin', drv:'yantracc', tool:'as', ext:'.asm', pipe:[]},
};
const HOSTKEY={guru:'c',praatha:'basic',shraeni:'cpp',kritrima:'java',soochee:'python',
  shabda:'lex',wyaaka:'yacc',yantra:'asm'};

const lang = process.argv[2];
const outDir = process.argv[3] || `hindawi-${lang}/Hindawi`;
if (!lang || !head.includes(lang)) {
  console.error(`usage: gen_perso_shaili.mjs <language> [outdir]`);
  console.error(`languages: ${head.filter((h)=>!['construct','standard','host','kind','iso_clause','std_ref'].includes(h)).join(' ')}`);
  process.exit(2);
}
const FLTR = { urdu:['fltr_ur_hi','fltr_hi_ur'], sindhi:['fltr_ur_hi','fltr_hi_ur'],
  kashmiri:['fltr_ur_hi','fltr_hi_ur'], shahmukhi:['fltr_ur_hi','fltr_hi_ur'],
  persian:['fltr_ur_hi','fltr_hi_ur'], dari:['fltr_ur_hi','fltr_hi_ur'],
  pashto:['fltr_ur_hi','fltr_hi_ur'], arabic:['fltr_ur_hi','fltr_hi_ur'],
  telugu:['fltr_te_hi','fltr_hi_te'] };
const [toHi, fromHi] = FLTR[lang] || ['fltr_ur_hi','fltr_hi_ur'];

// Rules retrieved from each transducer, so nothing is dropped.
function retrieved(file) {
  const out=[]; const p=path.join(LEG,file);
  if (!fs.existsSync(p)) return out;
  for (const l of fs.readFileSync(p,'utf8').split('\n')) {
    const m=l.match(/^(\S+)(\s+)\{printf\("([^"]*)"\);\}\s*$/);
    if (m) out.push({from:m[1], gap:m[2], to:m[3]});
  }
  return out;
}
const HDR = (what) => `<शैली शब्द>
%{
/* ${what}
 * Copyright (C) 1993-2026 Abhishek Choudhary
 * Hindawi Indic Programming System.  GNU GPL v2 or later.
 *
 * Generated by tools/gen_perso_shaili.mjs from ilm/keywords.csv.
 * Built through:  fixuninum | ${toHi} | iconv -f utf-8 -t utf-16 | uni2acii | acii2cf | tail +2
 * The build must NOT pipe this through h2c — that transduces the pattern
 * column too and the rules stop matching.
 */
%}
%%
`;
fs.mkdirSync(path.join(root,outDir),{recursive:true});
const report=[];
for (const [sh,cfg] of Object.entries(SH)) {
  const hk=HOSTKEY[sh];
  const words=new Map();            // host keyword -> native word
  for (const r of rows) if (r.host===hk && r[lang]) words.set(r.standard, r[lang]);
  const base=retrieved(cfg.src);
  const dir=path.join(root,outDir,sh); fs.mkdirSync(dir,{recursive:true});

  // FORWARD: native pattern -> plain ASCII host keyword
  const f=[HDR(`${lang} -> ${cfg.host}  (forward)`)];
  let n=0, carried=0;
  for (const r of base) {
    const w=words.get(r.to);
    if (w) { f.push(`${w}\t\t{printf("${r.to}");}`); n++; }
    else { f.push(`${r.from}${r.gap}{printf("${r.to}");}`); carried++; }
  }
  f.push('\n%%\n');
  fs.writeFileSync(path.join(dir,`${cfg.fwd}_${lang}.uhin`), f.join('\n'));

  // REVERSE: plain ASCII host keyword -> native word (emerges as romenagri;
  // the driver pipes the output through fromHi to restore the script)
  const b=[HDR(`${cfg.host} -> ${lang}  (reverse; output piped through ${fromHi})`)];
  for (const r of base) { const w=words.get(r.to); if (w) b.push(`${r.to}\t\t{printf("${w}");}`); }
  b.push('\n%%\n');
  fs.writeFileSync(path.join(dir,`${cfg.rev}_${lang}.uhin`), b.join('\n'));

  // Makefile — the chain, with tail +2 to drop the shaili line
  fs.writeFileSync(path.join(dir,'Makefile'),
`#Copyright (C) 1993-2026 Abhishek Choudhary. GPL v2 or later.
#Hindawi — shaili ${sh} (${cfg.host}) — ${lang}
EXECDIR=/usr/bin
CHAIN=fixuninum | ${toHi} | iconv -f utf-8 -t utf-16 | uni2acii | acii2cf | tail +2

all: ${cfg.fwd}_${lang} ${cfg.rev}_${lang}

${cfg.fwd}_${lang}: ${cfg.fwd}_${lang}.uhin
\tcat ${cfg.fwd}_${lang}.uhin | $(CHAIN) > ${cfg.fwd}_${lang}.lex
\tflex -8 -olexyy.c ${cfg.fwd}_${lang}.lex
\tgcc lexyy.c -o${cfg.fwd}_${lang} -lfl

${cfg.rev}_${lang}: ${cfg.rev}_${lang}.uhin
\tcat ${cfg.rev}_${lang}.uhin | $(CHAIN) > ${cfg.rev}_${lang}.lex
\tflex -8 -olexyy.c ${cfg.rev}_${lang}.lex
\tgcc lexyy.c -o${cfg.rev}_${lang} -lfl

install:
\tinstall ${cfg.fwd}_${lang} $(INSTROOT)$(EXECDIR)/${cfg.fwd}_${lang}
\tinstall ${cfg.rev}_${lang} $(INSTROOT)$(EXECDIR)/${cfg.rev}_${lang}
\tinstall ${cfg.drv}_${lang} $(INSTROOT)$(EXECDIR)/${cfg.drv}_${lang}

clean_all: clean
clean:
\trm -f lexyy.c *.lex ${cfg.fwd}_${lang} ${cfg.rev}_${lang}
`);
  // driver
  const chain=[`./${cfg.fwd}_${lang}`, ...cfg.pipe].join(' | ');
  fs.writeFileSync(path.join(dir,`${cfg.drv}_${lang}`),
`#!/bin/bash
#Copyright (C) 1993-2026 Abhishek Choudhary. GPL v2 or later.
#Hindawi — shaili ${sh} (${cfg.host}) — ${lang}
#Forward:  native source -> ${cfg.host}.  The .lex is never piped through h2c.
echo संकलन के परिणाम >  tempfil0123.tmphin
echo ============ >> tempfil0123.tmphin
cat $1 | fixuninum | fixarabnum | ${toHi} | iconv -f utf-8 -t utf-16 | uni2acii | acii2cf \\
  | ${chain} > tempfil0123.tmphin${cfg.ext}
${cfg.tool} tempfil0123.tmphin${cfg.ext} 2>> tempfil0123.tmphin
cat tempfil0123.tmphin
rm tempfil0123.tmphin
`,{mode:0o755});
  // reverse driver — output returns to the native script
  fs.writeFileSync(path.join(dir,`${cfg.drv}_${lang}_rev`),
`#!/bin/bash
#Reverse: ${cfg.host} source -> ${lang}. Output passes through ${fromHi}
#because the action strings emerged from the build chain as romenagri.
cat $1 | ./${cfg.rev}_${lang} | ${fromHi}
`,{mode:0o755});
  report.push({shaili:sh, host:cfg.host, rules:base.length, localised:n, carried});
}
// The numerals gap he found: fixuninum handles Devanagari digits only.
fs.writeFileSync(path.join(root,outDir,'fixarabnum'),
`#!/bin/sh
# fixarabnum — Arabic-Indic and Eastern Arabic-Indic digits to ASCII.
# Copyright (C) 1993-2026 Abhishek Choudhary. GPL v2 or later.
#
# fixuninum converts Devanagari digits (U+0966-096F). It does NOT cover
# U+0660-0669 (Arabic-Indic) or U+06F0-06F9 (Eastern Arabic-Indic, used by
# Urdu, Persian, Pashto, Dari and Sindhi), so a literal like [۸۰] reached the
# C compiler as an undeclared identifier. This closes that gap.
sed -e 'y/٠١٢٣٤٥٦٧٨٩/0123456789/' -e 'y/۰۱۲۳۴۵۶۷۸۹/0123456789/'
`,{mode:0o755});
console.log(`${lang} -> ${outDir}`);
console.log('shaili'.padEnd(10)+'host'.padEnd(8)+'rules'.padStart(6)+'  localised  carried');
for (const r of report)
  console.log(r.shaili.padEnd(10)+r.host.padEnd(8)+String(r.rules).padStart(6)+String(r.localised).padStart(11)+String(r.carried).padStart(9));
console.log(`\nfixarabnum written — the numerals gap fixuninum does not cover.`);
